# Introduction to the JupyterLab and Jupyter Notebooks

This is a short introduction to two of the flagship tools created by [the Jupyter Community](https://jupyter.org).

> **⚠️Experimental!⚠️**: This is an experimental interface provided by the [JupyterLite project](https://jupyterlite.readthedocs.io/en/latest/). It embeds an entire JupyterLab interface, with many popular packages for scientific computing, in your browser. There may be minor differences in behavior between JupyterLite and the JupyterLab you install locally. You may also encounter some bugs or unexpected behavior. To report any issues, or to get involved with the JupyterLite project, see [the JupyterLite repository](https://github.com/jupyterlite/jupyterlite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

## JupyterLab 🧪

**JupyterLab** is a next-generation web-based user interface for Project Jupyter. It enables you to work with documents and activities such as Jupyter notebooks, text editors, terminals, and custom components in a flexible, integrated, and extensible manner. It is the interface that you're looking at right now.

**For an overview of the JupyterLab interface**, see the **JupyterLab Welcome Tour** on this page, by going to `Help -> Welcome Tour` and following the prompts.

> **See Also**: For a more in-depth tour of JupyterLab with a full environment that runs in the cloud, see [the JupyterLab introduction on Binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/HEAD?urlpath=lab/tree/demo).

## Jupyter Notebooks 📓

**Jupyter Notebooks** are a community standard for communicating and performing interactive computing. They are a document that blends computations, outputs, explanatory text, mathematics, images, and rich media representations of objects.

JupyterLab is one interface used to create and interact with Jupyter Notebooks.

**For an overview of Jupyter Notebooks**, see the **JupyterLab Welcome Tour** on this page, by going to `Help -> Notebook Tour` and following the prompts.

> **See Also**: For a more in-depth tour of Jupyter Notebooks and the Classic Jupyter Notebook interface, see [the Jupyter Notebook IPython tutorial on Binder](https://mybinder.org/v2/gh/ipython/ipython-in-depth/HEAD?urlpath=tree/binder/Index.ipynb).

## An example: visualizing data in the notebook ✨

Below is an example of a code cell. We'll visualize some simple data using two popular packages in Python. We'll use [NumPy](https://numpy.org/) to create some random data, and [Matplotlib](https://matplotlib.org) to visualize it.

Note how the code and the results of running the code are bundled together.

In [8]:
'''
1)	Define the following metrics and perform the following operations
i)	Write a Python program using Python Lists
ii)	Write a Python program and NumPy

Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] ,
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] ,
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] ,
[1.1254  2.8956,  5.9187]].'''

'\n1)\tDefine the following metrics and perform the following operations\ni)\tWrite a Python program using Python Lists\nii)\tWrite a Python program and NumPy\n\nMatrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] ,\n[1.1234  2.8934,  5.9087]].\n\nMatrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] ,\n[1.0987  1.3456,  5.1234]].\n\nMatrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] ,\n[1.1254  2.8956,  5.9187]].'

In [2]:
#Define matrices
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

In [ ]:
#Using python lists

In [4]:
#Addition operation of matrix A and matrix B
result = [[A[i][j] + B[i][j]  for j in range(len(A[0]))] for i in range(len(A))]

for r in result:
   print(r)

[6.9061, 6.444100000000001, 6.3575]
[4.3233, 6.79, 7.242]
[2.2221, 4.239, 11.0321]


In [10]:
#Subtraction operation of matrix A and matrix C
result = [[A[i][j] - C[i][j]  for j in range(len(A[0]))] for i in range(len(A))]

for r in result:
   print(r)

[0.6584000000000003, 0.24650000000000016, 0.10850000000000026]
[-0.45989999999999975, -0.11070000000000002, 0.007000000000000117]
[-0.0020000000000000018, -0.0021999999999997577, -0.010000000000000675]


In [11]:
#Multiplication operation of matrix B and matrix C
result = [[sum(a*b for a,b in zip(B_row,C_col)) for C_col in zip(*C)] for B_row in B]

for r in result:
   print(r)

[21.55354925, 30.12178925, 40.33916441]
[18.957046169999998, 28.04685397, 38.89931461]
[12.794120529999999, 23.18986807, 39.008091820000004]


In [7]:
#Transpose of matrix A
for i in range(len(A)):
   # iterate through columns
   for j in range(len(A[0])):
       result[j][i] = A[i][j]

for r in result:
   print(r)

[3.7827, 2.2122, 1.1234]
[3.3454, 3.5678, 2.8934]
[3.2341, 3.9087, 5.9087]


In [9]:
#Transpose of matrix B
for i in range(len(B)):
   # iterate through columns
   for j in range(len(B[0])):
       result[j][i] = A[i][j]

for r in result:
   print(r)

[3.7827, 2.2122, 1.1234]
[3.3454, 3.5678, 2.8934]
[3.2341, 3.9087, 5.9087]


In [12]:
#Transpose of matrix C
for i in range(len(C)):
   # iterate through columns
   for j in range(len(C[0])):
       result[j][i] = C[i][j]

for r in result:
   print(r)

[3.1243, 2.6721, 1.1254]
[3.0989, 3.6785, 2.8956]
[3.1256, 3.9017, 5.9187]


In [19]:
#ii.Using Numpy

In [15]:
import numpy as np

In [18]:
matrix1= np.array(A)
matrix2=np.array(B)
matrix3=np.array(C)
sum1=np.add(matrix1,matrix2)
print(sum1)
sub2=np.subtract(matrix1,matrix3)
print(sub2)
mul=np.multiply(matrix1,matrix3)
print(mul)
tran=matrix1.transpose()
print(tran)

[[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]
[[ 0.6584  0.2465  0.1085]
 [-0.4599 -0.1107  0.007 ]
 [-0.002  -0.0022 -0.01  ]]
[[11.81828961 10.36706006 10.10850296]
 [ 5.91121962 13.1241523  15.25057479]
 [ 1.26427436  8.37812904 34.97182269]]
[[3.7827 2.2122 1.1234]
 [3.3454 3.5678 2.8934]
 [3.2341 3.9087 5.9087]]


## Next steps 🏃

This is just a short introduction to JupyterLab and Jupyter Notebooks. See below for some more ways to interact with tools in the Jupyter ecosystem, and its community.

### Other notebooks in this demo

Here are some other notebooks in this demo. Each of the items below corresponds to a file or folder in the **file browser to the left**.

- [**`Lorenz.ipynb`**](Lorenz.ipynb) uses Python to demonstrate interactive visualizations and computations around the [Lorenz system](https://en.wikipedia.org/wiki/Lorenz_system). It shows off basic Python functionality, including more visualizations, data structures, and scientific computing libraries.
- [**`sqlite.ipynb`**](sqlite.ipynb) demonstrates how an in-browser sqlite kernel to run your own SQL commands from the notebook. It uses the [jupyterlite/xeus-sqlite-kernel](https://github.com/jupyterlite/xeus-sqlite-kernel).

### Other sources of information in Jupyter

- **More on using JupyterLab**: See [the JupyterLab documentation](https://jupyterlab.readthedocs.io/en/stable/) for more thorough information about how to install and use JupyterLab.
- **More interactive demos**: See [try.jupyter.org](https://try.jupyter.org) for more interactive demos with the Jupyter ecosystem.
- **Learn more about Jupyter**: See [the Jupyter community documentation](https://docs.jupyter.org) to learn more about the project, its community and tools, and how to get involved.
- **Join our discussions**: The [Jupyter Community Forum](https://discourse.jupyter.org) is a place where many in the Jupyter community ask questions, help one another, and discuss issues around interactive computing and our ecosystem.